/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";

export class Characters extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Character metadata
     *
     * @remarks
     * Get data for available characters in the system. Paginated. Up to 100 characters per request
     */
    async list(
        numCharacters: number,
        from?: number | undefined,
        options?: RequestOptions
    ): Promise<operations.CharactersListResponse> {
        const input$: operations.CharactersListRequest = {
            numCharacters: numCharacters,
            from: from,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.CharactersListRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v6/characters")();

        const query$ = encodeFormQuery$({
            from: payload$.from,
            numCharacters: payload$.numCharacters,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = { operationID: "characters.list", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["5XX"],
            retryConfig: options?.retries ||
                this.options$.retryConfig || {
                    strategy: "backoff",
                    backoff: {
                        initialInterval: 1000,
                        maxInterval: 60000,
                        exponent: 1.2,
                        maxElapsedTime: 3600000,
                    },
                    retryConnectionErrors: true,
                },
            retryCodes: options?.retryCodes || ["5XX"],
        });

        const [result$] = await this.matcher<operations.CharactersListResponse>()
            .json(200, operations.CharactersListResponse$inboundSchema)
            .json(400, operations.CharactersListResponse$inboundSchema)
            .json(401, operations.CharactersListResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Character banner image
     */
    async banner(
        characterId: number,
        options?: RequestOptions
    ): Promise<operations.CharactersBannerResponse> {
        const input$: operations.CharactersBannerRequest = {
            characterId: characterId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.CharactersBannerRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v6/characters/banner")();

        const query$ = encodeFormQuery$({
            characterId: payload$.characterId,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = {
            operationID: "characters.banner",
            oAuth2Scopes: [],
            securitySource: null,
        };

        const request$ = this.createRequest$(
            context,
            {
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["5XX"],
            retryConfig: options?.retries ||
                this.options$.retryConfig || {
                    strategy: "backoff",
                    backoff: {
                        initialInterval: 1000,
                        maxInterval: 60000,
                        exponent: 1.2,
                        maxElapsedTime: 3600000,
                    },
                    retryConnectionErrors: true,
                },
            retryCodes: options?.retryCodes || ["5XX"],
        });

        const [result$] = await this.matcher<operations.CharactersBannerResponse>()
            .json(200, operations.CharactersBannerResponse$inboundSchema)
            .json(400, operations.CharactersBannerResponse$inboundSchema)
            .json(401, operations.CharactersBannerResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Get information about a character
     */
    async get(
        characterId: number,
        options?: RequestOptions
    ): Promise<operations.CharactersGetResponse> {
        const input$: operations.CharactersGetRequest = {
            characterId: characterId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.CharactersGetRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v6/character")();

        const query$ = encodeFormQuery$({
            characterId: payload$.characterId,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = { operationID: "characters.get", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["5XX"],
            retryConfig: options?.retries ||
                this.options$.retryConfig || {
                    strategy: "backoff",
                    backoff: {
                        initialInterval: 1000,
                        maxInterval: 60000,
                        exponent: 1.2,
                        maxElapsedTime: 3600000,
                    },
                    retryConnectionErrors: true,
                },
            retryCodes: options?.retryCodes || ["5XX"],
        });

        const [result$] = await this.matcher<operations.CharactersGetResponse>()
            .json(200, operations.CharactersGetResponse$inboundSchema)
            .json(400, operations.CharactersGetResponse$inboundSchema)
            .json(401, operations.CharactersGetResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Create character
     *
     * @remarks
     * Upload character data to our system
     */
    async create(
        request?: operations.CharactersCreateRequestBody | undefined,
        options?: RequestOptions
    ): Promise<operations.CharactersCreateResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.CharactersCreateRequestBody$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/v6/character")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = {
            operationID: "characters.create",
            oAuth2Scopes: [],
            securitySource: null,
        };

        const request$ = this.createRequest$(
            context,
            {
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["5XX"],
            retryConfig: options?.retries ||
                this.options$.retryConfig || {
                    strategy: "backoff",
                    backoff: {
                        initialInterval: 1000,
                        maxInterval: 60000,
                        exponent: 1.2,
                        maxElapsedTime: 3600000,
                    },
                    retryConnectionErrors: true,
                },
            retryCodes: options?.retryCodes || ["5XX"],
        });

        const [result$] = await this.matcher<operations.CharactersCreateResponse>()
            .json(200, operations.CharactersCreateResponse$inboundSchema)
            .json(400, operations.CharactersCreateResponse$inboundSchema)
            .json(401, operations.CharactersCreateResponse$inboundSchema)
            .json(402, operations.CharactersCreateResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }
}
