/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as retries$ from "../lib/retries.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";

export enum SendAcceptEnum {
    applicationJson = "application/json",
    textEventStream = "text/event-stream",
}

export class Messages extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Save chat message
     *
     * @remarks
     * Save chat message either from the initial context prompt or after AI generation
     */
    async save(
        role: operations.Role,
        content: string,
        timestamp: number,
        chatId: number,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.SaveMessageResponse> {
        const input$: operations.SaveMessageTimestampedMessageResponse | undefined = {
            role: role,
            content: content,
            timestamp: timestamp,
            chatId: chatId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.SaveMessageTimestampedMessageResponse$outboundSchema.optional().parse(
                    value$
                ),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/v4/saveMessage")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = { operationID: "saveMessage", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 1000,
                    maxInterval: 60000,
                    exponent: 1.2,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, { context, errorCodes: ["5XX"] });
            },
            { config: retryConfig, statusCodes: ["5XX"] }
        );

        const [result$] = await this.matcher<operations.SaveMessageResponse>()
            .json(200, operations.SaveMessageResponse$inboundSchema)
            .json(400, operations.SaveMessageResponse$inboundSchema)
            .json(401, operations.SaveMessageResponse$inboundSchema)
            .json(402, operations.SaveMessageResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Get full message history
     *
     * @remarks
     * Get all of the messages sent in a given chat
     */
    async history(
        chatId: number,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.GetMessageHistoryResponse> {
        const input$: operations.GetMessageHistoryRequest = {
            chatId: chatId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetMessageHistoryRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v4/getMessageHistory")();

        const query$ = encodeFormQuery$({
            chatId: payload$.chatId,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = {
            operationID: "getMessageHistory",
            oAuth2Scopes: [],
            securitySource: null,
        };

        const request$ = this.createRequest$(
            context,
            {
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 1000,
                    maxInterval: 60000,
                    exponent: 1.2,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, { context, errorCodes: ["5XX"] });
            },
            { config: retryConfig, statusCodes: ["5XX"] }
        );

        const [result$] = await this.matcher<operations.GetMessageHistoryResponse>()
            .json(200, operations.GetMessageHistoryResponse$inboundSchema)
            .json(400, operations.GetMessageHistoryResponse$inboundSchema)
            .json(401, operations.GetMessageHistoryResponse$inboundSchema)
            .json(402, operations.GetMessageHistoryResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Get chat context
     *
     * @remarks
     * Get all the messages from a given chat that are allocated to be used as AI model context. Almost always less messages than full chat history for performance reasons when running against our AI model.
     */
    async context(
        chatId: number,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.GetMessageContextResponse> {
        const input$: operations.GetMessageContextRequest = {
            chatId: chatId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetMessageContextRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v4/getMessageContext")();

        const query$ = encodeFormQuery$({
            chatId: payload$.chatId,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = {
            operationID: "getMessageContext",
            oAuth2Scopes: [],
            securitySource: null,
        };

        const request$ = this.createRequest$(
            context,
            {
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 1000,
                    maxInterval: 60000,
                    exponent: 1.2,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, { context, errorCodes: ["5XX"] });
            },
            { config: retryConfig, statusCodes: ["5XX"] }
        );

        const [result$] = await this.matcher<operations.GetMessageContextResponse>()
            .json(200, operations.GetMessageContextResponse$inboundSchema)
            .json(400, operations.GetMessageContextResponse$inboundSchema)
            .json(401, operations.GetMessageContextResponse$inboundSchema)
            .json(402, operations.GetMessageContextResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Send message
     *
     * @remarks
     * Send a chat message to a particular chat for a response
     */
    async send(
        chatId: number,
        message: string,
        messageContext?: Array<components.Message> | undefined,
        options?: RequestOptions & {
            acceptHeaderOverride?: SendAcceptEnum;
            retries?: retries$.RetryConfig;
        }
    ): Promise<operations.SendMessageResponse> {
        const input$: operations.SendMessageChatIDResponse | undefined = {
            chatId: chatId,
            message: message,
            messageContext: messageContext,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.SendMessageChatIDResponse$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/v4/sendMessage")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: options?.acceptHeaderOverride || "application/json;q=1, text/event-stream;q=0",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = { operationID: "sendMessage", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 1000,
                    maxInterval: 60000,
                    exponent: 1.2,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, { context, errorCodes: ["5XX"] });
            },
            { config: retryConfig, statusCodes: ["5XX"] }
        );

        const [result$] = await this.matcher<operations.SendMessageResponse>()
            .sse(200, operations.SendMessageResponse$inboundSchema)
            .json(400, operations.SendMessageResponse$inboundSchema)
            .json(401, operations.SendMessageResponse$inboundSchema)
            .json(402, operations.SendMessageResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }

    /**
     * Delete message
     *
     * @remarks
     * Remove message from message history, given a message ID
     */
    async delete(
        messageId: number,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.DeleteMessageResponse> {
        const input$: operations.DeleteMessageRequest = {
            messageId: messageId,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteMessageRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/v4/deleteMessage")();

        const query$ = encodeFormQuery$({
            messageId: payload$.messageId,
        });

        const headers$ = new Headers({
            Accept: "application/json",
            "x-access-token": encodeSimple$("x-access-token", this.options$.accessToken, {
                explode: false,
                charEncoding: "none",
            }),
        });

        const context = { operationID: "deleteMessage", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 1000,
                    maxInterval: 60000,
                    exponent: 1.2,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, { context, errorCodes: ["5XX"] });
            },
            { config: retryConfig, statusCodes: ["5XX"] }
        );

        const [result$] = await this.matcher<operations.DeleteMessageResponse>()
            .json(200, operations.DeleteMessageResponse$inboundSchema)
            .json(400, operations.DeleteMessageResponse$inboundSchema)
            .json(401, operations.DeleteMessageResponse$inboundSchema)
            .json(402, operations.DeleteMessageResponse$inboundSchema)
            .fail("5XX")
            .match(response);

        return result$;
    }
}
