/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Characters } from "./characters.js";
import { Chats } from "./chats.js";
import { Messages } from "./messages.js";
import { Users } from "./users.js";

export class AuroraChatbotSDK extends ClientSDK {
    private _users?: Users;
    get users(): Users {
        return (this._users ??= new Users(this.options$));
    }

    private _characters?: Characters;
    get characters(): Characters {
        return (this._characters ??= new Characters(this.options$));
    }

    private _chats?: Chats;
    get chats(): Chats {
        return (this._chats ??= new Chats(this.options$));
    }

    private _messages?: Messages;
    get messages(): Messages {
        return (this._messages ??= new Messages(this.options$));
    }
}
