/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteChatGlobals = {
    accessToken?: string | undefined;
};

export type DeleteChatRequest = {
    chatId: number;
};

/** @internal */
export namespace DeleteChatGlobals$ {
    export const inboundSchema: z.ZodType<DeleteChatGlobals, z.ZodTypeDef, unknown> = z.object({
        accessToken: z.string().optional(),
    });

    export type Outbound = {
        accessToken?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteChatGlobals> = z.object({
        accessToken: z.string().optional(),
    });
}

/** @internal */
export namespace DeleteChatRequest$ {
    export const inboundSchema: z.ZodType<DeleteChatRequest, z.ZodTypeDef, unknown> = z.object({
        chatId: z.number().int(),
    });

    export type Outbound = {
        chatId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteChatRequest> = z.object({
        chatId: z.number().int(),
    });
}
