/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetCharacterAiInitializationDataGlobals = {
    accessToken?: string | undefined;
};

export type GetCharacterAiInitializationDataRequest = {
    characterId: number;
};

/**
 * Character AI initialization data
 */
export type GetCharacterAiInitializationDataSuccessfulRequest = {
    aiPrompt: string;
    initialResponse: string;
    success?: boolean | undefined;
};

/** @internal */
export namespace GetCharacterAiInitializationDataGlobals$ {
    export const inboundSchema: z.ZodType<
        GetCharacterAiInitializationDataGlobals,
        z.ZodTypeDef,
        unknown
    > = z.object({
        accessToken: z.string().optional(),
    });

    export type Outbound = {
        accessToken?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetCharacterAiInitializationDataGlobals
    > = z.object({
        accessToken: z.string().optional(),
    });
}

/** @internal */
export namespace GetCharacterAiInitializationDataRequest$ {
    export const inboundSchema: z.ZodType<
        GetCharacterAiInitializationDataRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        characterId: z.number().int(),
    });

    export type Outbound = {
        characterId: number;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetCharacterAiInitializationDataRequest
    > = z.object({
        characterId: z.number().int(),
    });
}

/** @internal */
export namespace GetCharacterAiInitializationDataSuccessfulRequest$ {
    export const inboundSchema: z.ZodType<
        GetCharacterAiInitializationDataSuccessfulRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        aiPrompt: z.string(),
        initialResponse: z.string(),
        success: z.boolean().default(true),
    });

    export type Outbound = {
        aiPrompt: string;
        initialResponse: string;
        success: boolean;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetCharacterAiInitializationDataSuccessfulRequest
    > = z.object({
        aiPrompt: z.string(),
        initialResponse: z.string(),
        success: z.boolean().default(true),
    });
}
