/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type InitializeChatGlobals = {
    accessToken?: string | undefined;
};

export type InitializeChatResponse =
    | components.SuccessfulRequest
    | components.BadRequestError
    | components.AuthenticationFailedError
    | components.AccountInBadStandingError;

/** @internal */
export const InitializeChatGlobals$inboundSchema: z.ZodType<
    InitializeChatGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    accessToken: z.string().optional(),
});

/** @internal */
export type InitializeChatGlobals$Outbound = {
    accessToken?: string | undefined;
};

/** @internal */
export const InitializeChatGlobals$outboundSchema: z.ZodType<
    InitializeChatGlobals$Outbound,
    z.ZodTypeDef,
    InitializeChatGlobals
> = z.object({
    accessToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InitializeChatGlobals$ {
    /** @deprecated use `InitializeChatGlobals$inboundSchema` instead. */
    export const inboundSchema = InitializeChatGlobals$inboundSchema;
    /** @deprecated use `InitializeChatGlobals$outboundSchema` instead. */
    export const outboundSchema = InitializeChatGlobals$outboundSchema;
    /** @deprecated use `InitializeChatGlobals$Outbound` instead. */
    export type Outbound = InitializeChatGlobals$Outbound;
}

/** @internal */
export const InitializeChatResponse$inboundSchema: z.ZodType<
    InitializeChatResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.SuccessfulRequest$inboundSchema,
    components.BadRequestError$inboundSchema,
    components.AuthenticationFailedError$inboundSchema,
    components.AccountInBadStandingError$inboundSchema,
]);

/** @internal */
export type InitializeChatResponse$Outbound =
    | components.SuccessfulRequest$Outbound
    | components.BadRequestError$Outbound
    | components.AuthenticationFailedError$Outbound
    | components.AccountInBadStandingError$Outbound;

/** @internal */
export const InitializeChatResponse$outboundSchema: z.ZodType<
    InitializeChatResponse$Outbound,
    z.ZodTypeDef,
    InitializeChatResponse
> = z.union([
    components.SuccessfulRequest$outboundSchema,
    components.BadRequestError$outboundSchema,
    components.AuthenticationFailedError$outboundSchema,
    components.AccountInBadStandingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InitializeChatResponse$ {
    /** @deprecated use `InitializeChatResponse$inboundSchema` instead. */
    export const inboundSchema = InitializeChatResponse$inboundSchema;
    /** @deprecated use `InitializeChatResponse$outboundSchema` instead. */
    export const outboundSchema = InitializeChatResponse$outboundSchema;
    /** @deprecated use `InitializeChatResponse$Outbound` instead. */
    export type Outbound = InitializeChatResponse$Outbound;
}
