/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type InitializeChatGlobals = {
    accessToken?: string | undefined;
};

/** @internal */
export namespace InitializeChatGlobals$ {
    export const inboundSchema: z.ZodType<InitializeChatGlobals, z.ZodTypeDef, unknown> = z.object({
        accessToken: z.string().optional(),
    });

    export type Outbound = {
        accessToken?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InitializeChatGlobals> =
        z.object({
            accessToken: z.string().optional(),
        });
}
