/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type MessagesDeleteGlobals = {
    accessToken?: string | undefined;
};

export type MessagesDeleteRequest = {
    messageId: number;
};

export type MessagesDeleteResponse =
    | components.SuccessfulRequest
    | components.BadRequestError
    | components.AuthenticationFailedError
    | components.AccountInBadStandingError;

/** @internal */
export const MessagesDeleteGlobals$inboundSchema: z.ZodType<
    MessagesDeleteGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    accessToken: z.string().optional(),
});

/** @internal */
export type MessagesDeleteGlobals$Outbound = {
    accessToken?: string | undefined;
};

/** @internal */
export const MessagesDeleteGlobals$outboundSchema: z.ZodType<
    MessagesDeleteGlobals$Outbound,
    z.ZodTypeDef,
    MessagesDeleteGlobals
> = z.object({
    accessToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesDeleteGlobals$ {
    /** @deprecated use `MessagesDeleteGlobals$inboundSchema` instead. */
    export const inboundSchema = MessagesDeleteGlobals$inboundSchema;
    /** @deprecated use `MessagesDeleteGlobals$outboundSchema` instead. */
    export const outboundSchema = MessagesDeleteGlobals$outboundSchema;
    /** @deprecated use `MessagesDeleteGlobals$Outbound` instead. */
    export type Outbound = MessagesDeleteGlobals$Outbound;
}

/** @internal */
export const MessagesDeleteRequest$inboundSchema: z.ZodType<
    MessagesDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    messageId: z.number().int(),
});

/** @internal */
export type MessagesDeleteRequest$Outbound = {
    messageId: number;
};

/** @internal */
export const MessagesDeleteRequest$outboundSchema: z.ZodType<
    MessagesDeleteRequest$Outbound,
    z.ZodTypeDef,
    MessagesDeleteRequest
> = z.object({
    messageId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesDeleteRequest$ {
    /** @deprecated use `MessagesDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = MessagesDeleteRequest$inboundSchema;
    /** @deprecated use `MessagesDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = MessagesDeleteRequest$outboundSchema;
    /** @deprecated use `MessagesDeleteRequest$Outbound` instead. */
    export type Outbound = MessagesDeleteRequest$Outbound;
}

/** @internal */
export const MessagesDeleteResponse$inboundSchema: z.ZodType<
    MessagesDeleteResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.SuccessfulRequest$inboundSchema,
    components.BadRequestError$inboundSchema,
    components.AuthenticationFailedError$inboundSchema,
    components.AccountInBadStandingError$inboundSchema,
]);

/** @internal */
export type MessagesDeleteResponse$Outbound =
    | components.SuccessfulRequest$Outbound
    | components.BadRequestError$Outbound
    | components.AuthenticationFailedError$Outbound
    | components.AccountInBadStandingError$Outbound;

/** @internal */
export const MessagesDeleteResponse$outboundSchema: z.ZodType<
    MessagesDeleteResponse$Outbound,
    z.ZodTypeDef,
    MessagesDeleteResponse
> = z.union([
    components.SuccessfulRequest$outboundSchema,
    components.BadRequestError$outboundSchema,
    components.AuthenticationFailedError$outboundSchema,
    components.AccountInBadStandingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesDeleteResponse$ {
    /** @deprecated use `MessagesDeleteResponse$inboundSchema` instead. */
    export const inboundSchema = MessagesDeleteResponse$inboundSchema;
    /** @deprecated use `MessagesDeleteResponse$outboundSchema` instead. */
    export const outboundSchema = MessagesDeleteResponse$outboundSchema;
    /** @deprecated use `MessagesDeleteResponse$Outbound` instead. */
    export type Outbound = MessagesDeleteResponse$Outbound;
}
