/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type MessagesGetManyGlobals = {
    accessToken?: string | undefined;
};

export type MessagesGetManyRequest = {
    chatId: number;
    numMessages: number;
    /**
     * Message ID to start results from (useful in pagination)
     */
    from?: number | undefined;
};

export const MessagesGetManyRole = {
    System: "system",
    User: "user",
    Assistant: "assistant",
} as const;
export type MessagesGetManyRole = ClosedEnum<typeof MessagesGetManyRole>;

export type MessagesGetManyTimestampedMessageResponse = {
    role: MessagesGetManyRole;
    content: string;
    timestamp: number;
    id: number;
};

/**
 * An array of messages that are part of the message history and an indicator of whether there are more messages left.
 */
export type MessagesGetManySuccessfulRequest = {
    success?: boolean | undefined;
    messages: Array<MessagesGetManyTimestampedMessageResponse>;
    endOfList: boolean;
};

export type MessagesGetManyResponse =
    | components.DefaultBadRequest
    | components.DefaultUnauthorizedResponse
    | components.DefaultBadStandingResponse
    | MessagesGetManySuccessfulRequest;

/** @internal */
export const MessagesGetManyGlobals$inboundSchema: z.ZodType<
    MessagesGetManyGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    accessToken: z.string().optional(),
});

/** @internal */
export type MessagesGetManyGlobals$Outbound = {
    accessToken?: string | undefined;
};

/** @internal */
export const MessagesGetManyGlobals$outboundSchema: z.ZodType<
    MessagesGetManyGlobals$Outbound,
    z.ZodTypeDef,
    MessagesGetManyGlobals
> = z.object({
    accessToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManyGlobals$ {
    /** @deprecated use `MessagesGetManyGlobals$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManyGlobals$inboundSchema;
    /** @deprecated use `MessagesGetManyGlobals$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManyGlobals$outboundSchema;
    /** @deprecated use `MessagesGetManyGlobals$Outbound` instead. */
    export type Outbound = MessagesGetManyGlobals$Outbound;
}

/** @internal */
export const MessagesGetManyRequest$inboundSchema: z.ZodType<
    MessagesGetManyRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    chatId: z.number().int(),
    numMessages: z.number().int(),
    from: z.number().int().optional(),
});

/** @internal */
export type MessagesGetManyRequest$Outbound = {
    chatId: number;
    numMessages: number;
    from?: number | undefined;
};

/** @internal */
export const MessagesGetManyRequest$outboundSchema: z.ZodType<
    MessagesGetManyRequest$Outbound,
    z.ZodTypeDef,
    MessagesGetManyRequest
> = z.object({
    chatId: z.number().int(),
    numMessages: z.number().int(),
    from: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManyRequest$ {
    /** @deprecated use `MessagesGetManyRequest$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManyRequest$inboundSchema;
    /** @deprecated use `MessagesGetManyRequest$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManyRequest$outboundSchema;
    /** @deprecated use `MessagesGetManyRequest$Outbound` instead. */
    export type Outbound = MessagesGetManyRequest$Outbound;
}

/** @internal */
export const MessagesGetManyRole$inboundSchema: z.ZodNativeEnum<typeof MessagesGetManyRole> =
    z.nativeEnum(MessagesGetManyRole);

/** @internal */
export const MessagesGetManyRole$outboundSchema: z.ZodNativeEnum<typeof MessagesGetManyRole> =
    MessagesGetManyRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManyRole$ {
    /** @deprecated use `MessagesGetManyRole$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManyRole$inboundSchema;
    /** @deprecated use `MessagesGetManyRole$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManyRole$outboundSchema;
}

/** @internal */
export const MessagesGetManyTimestampedMessageResponse$inboundSchema: z.ZodType<
    MessagesGetManyTimestampedMessageResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    role: MessagesGetManyRole$inboundSchema,
    content: z.string(),
    timestamp: z.number().int(),
    id: z.number().int(),
});

/** @internal */
export type MessagesGetManyTimestampedMessageResponse$Outbound = {
    role: string;
    content: string;
    timestamp: number;
    id: number;
};

/** @internal */
export const MessagesGetManyTimestampedMessageResponse$outboundSchema: z.ZodType<
    MessagesGetManyTimestampedMessageResponse$Outbound,
    z.ZodTypeDef,
    MessagesGetManyTimestampedMessageResponse
> = z.object({
    role: MessagesGetManyRole$outboundSchema,
    content: z.string(),
    timestamp: z.number().int(),
    id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManyTimestampedMessageResponse$ {
    /** @deprecated use `MessagesGetManyTimestampedMessageResponse$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManyTimestampedMessageResponse$inboundSchema;
    /** @deprecated use `MessagesGetManyTimestampedMessageResponse$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManyTimestampedMessageResponse$outboundSchema;
    /** @deprecated use `MessagesGetManyTimestampedMessageResponse$Outbound` instead. */
    export type Outbound = MessagesGetManyTimestampedMessageResponse$Outbound;
}

/** @internal */
export const MessagesGetManySuccessfulRequest$inboundSchema: z.ZodType<
    MessagesGetManySuccessfulRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    success: z.boolean().default(true),
    messages: z.array(z.lazy(() => MessagesGetManyTimestampedMessageResponse$inboundSchema)),
    endOfList: z.boolean(),
});

/** @internal */
export type MessagesGetManySuccessfulRequest$Outbound = {
    success: boolean;
    messages: Array<MessagesGetManyTimestampedMessageResponse$Outbound>;
    endOfList: boolean;
};

/** @internal */
export const MessagesGetManySuccessfulRequest$outboundSchema: z.ZodType<
    MessagesGetManySuccessfulRequest$Outbound,
    z.ZodTypeDef,
    MessagesGetManySuccessfulRequest
> = z.object({
    success: z.boolean().default(true),
    messages: z.array(z.lazy(() => MessagesGetManyTimestampedMessageResponse$outboundSchema)),
    endOfList: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManySuccessfulRequest$ {
    /** @deprecated use `MessagesGetManySuccessfulRequest$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManySuccessfulRequest$inboundSchema;
    /** @deprecated use `MessagesGetManySuccessfulRequest$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManySuccessfulRequest$outboundSchema;
    /** @deprecated use `MessagesGetManySuccessfulRequest$Outbound` instead. */
    export type Outbound = MessagesGetManySuccessfulRequest$Outbound;
}

/** @internal */
export const MessagesGetManyResponse$inboundSchema: z.ZodType<
    MessagesGetManyResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.DefaultBadRequest$inboundSchema,
    components.DefaultUnauthorizedResponse$inboundSchema,
    components.DefaultBadStandingResponse$inboundSchema,
    z.lazy(() => MessagesGetManySuccessfulRequest$inboundSchema),
]);

/** @internal */
export type MessagesGetManyResponse$Outbound =
    | components.DefaultBadRequest$Outbound
    | components.DefaultUnauthorizedResponse$Outbound
    | components.DefaultBadStandingResponse$Outbound
    | MessagesGetManySuccessfulRequest$Outbound;

/** @internal */
export const MessagesGetManyResponse$outboundSchema: z.ZodType<
    MessagesGetManyResponse$Outbound,
    z.ZodTypeDef,
    MessagesGetManyResponse
> = z.union([
    components.DefaultBadRequest$outboundSchema,
    components.DefaultUnauthorizedResponse$outboundSchema,
    components.DefaultBadStandingResponse$outboundSchema,
    z.lazy(() => MessagesGetManySuccessfulRequest$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetManyResponse$ {
    /** @deprecated use `MessagesGetManyResponse$inboundSchema` instead. */
    export const inboundSchema = MessagesGetManyResponse$inboundSchema;
    /** @deprecated use `MessagesGetManyResponse$outboundSchema` instead. */
    export const outboundSchema = MessagesGetManyResponse$outboundSchema;
    /** @deprecated use `MessagesGetManyResponse$Outbound` instead. */
    export type Outbound = MessagesGetManyResponse$Outbound;
}
