/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type UsersGetUserInfoGlobals = {
    accessToken?: string | undefined;
};

export type UsersGetUserInfoRequest = {};

export type UsersGetUserInfoResponse = components.UserInfo | components.AuthenticationFailedError;

/** @internal */
export const UsersGetUserInfoGlobals$inboundSchema: z.ZodType<
    UsersGetUserInfoGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    accessToken: z.string().optional(),
});

/** @internal */
export type UsersGetUserInfoGlobals$Outbound = {
    accessToken?: string | undefined;
};

/** @internal */
export const UsersGetUserInfoGlobals$outboundSchema: z.ZodType<
    UsersGetUserInfoGlobals$Outbound,
    z.ZodTypeDef,
    UsersGetUserInfoGlobals
> = z.object({
    accessToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersGetUserInfoGlobals$ {
    /** @deprecated use `UsersGetUserInfoGlobals$inboundSchema` instead. */
    export const inboundSchema = UsersGetUserInfoGlobals$inboundSchema;
    /** @deprecated use `UsersGetUserInfoGlobals$outboundSchema` instead. */
    export const outboundSchema = UsersGetUserInfoGlobals$outboundSchema;
    /** @deprecated use `UsersGetUserInfoGlobals$Outbound` instead. */
    export type Outbound = UsersGetUserInfoGlobals$Outbound;
}

/** @internal */
export const UsersGetUserInfoRequest$inboundSchema: z.ZodType<
    UsersGetUserInfoRequest,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UsersGetUserInfoRequest$Outbound = {};

/** @internal */
export const UsersGetUserInfoRequest$outboundSchema: z.ZodType<
    UsersGetUserInfoRequest$Outbound,
    z.ZodTypeDef,
    UsersGetUserInfoRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersGetUserInfoRequest$ {
    /** @deprecated use `UsersGetUserInfoRequest$inboundSchema` instead. */
    export const inboundSchema = UsersGetUserInfoRequest$inboundSchema;
    /** @deprecated use `UsersGetUserInfoRequest$outboundSchema` instead. */
    export const outboundSchema = UsersGetUserInfoRequest$outboundSchema;
    /** @deprecated use `UsersGetUserInfoRequest$Outbound` instead. */
    export type Outbound = UsersGetUserInfoRequest$Outbound;
}

/** @internal */
export const UsersGetUserInfoResponse$inboundSchema: z.ZodType<
    UsersGetUserInfoResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.UserInfo$inboundSchema,
    components.AuthenticationFailedError$inboundSchema,
]);

/** @internal */
export type UsersGetUserInfoResponse$Outbound =
    | components.UserInfo$Outbound
    | components.AuthenticationFailedError$Outbound;

/** @internal */
export const UsersGetUserInfoResponse$outboundSchema: z.ZodType<
    UsersGetUserInfoResponse$Outbound,
    z.ZodTypeDef,
    UsersGetUserInfoResponse
> = z.union([
    components.UserInfo$outboundSchema,
    components.AuthenticationFailedError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersGetUserInfoResponse$ {
    /** @deprecated use `UsersGetUserInfoResponse$inboundSchema` instead. */
    export const inboundSchema = UsersGetUserInfoResponse$inboundSchema;
    /** @deprecated use `UsersGetUserInfoResponse$outboundSchema` instead. */
    export const outboundSchema = UsersGetUserInfoResponse$outboundSchema;
    /** @deprecated use `UsersGetUserInfoResponse$Outbound` instead. */
    export type Outbound = UsersGetUserInfoResponse$Outbound;
}
