/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type UsersLoginRequestBody = {
    username: string;
    password: string;
};

export type UsersLoginResponse =
    | components.AccessTokenObj
    | components.BadRequestError
    | components.AuthenticationFailedError;

/** @internal */
export const UsersLoginRequestBody$inboundSchema: z.ZodType<
    UsersLoginRequestBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    username: z.string(),
    password: z.string(),
});

/** @internal */
export type UsersLoginRequestBody$Outbound = {
    username: string;
    password: string;
};

/** @internal */
export const UsersLoginRequestBody$outboundSchema: z.ZodType<
    UsersLoginRequestBody$Outbound,
    z.ZodTypeDef,
    UsersLoginRequestBody
> = z.object({
    username: z.string(),
    password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersLoginRequestBody$ {
    /** @deprecated use `UsersLoginRequestBody$inboundSchema` instead. */
    export const inboundSchema = UsersLoginRequestBody$inboundSchema;
    /** @deprecated use `UsersLoginRequestBody$outboundSchema` instead. */
    export const outboundSchema = UsersLoginRequestBody$outboundSchema;
    /** @deprecated use `UsersLoginRequestBody$Outbound` instead. */
    export type Outbound = UsersLoginRequestBody$Outbound;
}

/** @internal */
export const UsersLoginResponse$inboundSchema: z.ZodType<
    UsersLoginResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.AccessTokenObj$inboundSchema,
    components.BadRequestError$inboundSchema,
    components.AuthenticationFailedError$inboundSchema,
]);

/** @internal */
export type UsersLoginResponse$Outbound =
    | components.AccessTokenObj$Outbound
    | components.BadRequestError$Outbound
    | components.AuthenticationFailedError$Outbound;

/** @internal */
export const UsersLoginResponse$outboundSchema: z.ZodType<
    UsersLoginResponse$Outbound,
    z.ZodTypeDef,
    UsersLoginResponse
> = z.union([
    components.AccessTokenObj$outboundSchema,
    components.BadRequestError$outboundSchema,
    components.AuthenticationFailedError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersLoginResponse$ {
    /** @deprecated use `UsersLoginResponse$inboundSchema` instead. */
    export const inboundSchema = UsersLoginResponse$inboundSchema;
    /** @deprecated use `UsersLoginResponse$outboundSchema` instead. */
    export const outboundSchema = UsersLoginResponse$outboundSchema;
    /** @deprecated use `UsersLoginResponse$Outbound` instead. */
    export type Outbound = UsersLoginResponse$Outbound;
}
