/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type UsersSetUserInfoGlobals = {
    accessToken?: string | undefined;
};

export type UsersSetUserInfoResponse =
    | components.SuccessfulRequest
    | components.BadRequestError
    | components.AuthenticationFailedError;

/** @internal */
export const UsersSetUserInfoGlobals$inboundSchema: z.ZodType<
    UsersSetUserInfoGlobals,
    z.ZodTypeDef,
    unknown
> = z.object({
    accessToken: z.string().optional(),
});

/** @internal */
export type UsersSetUserInfoGlobals$Outbound = {
    accessToken?: string | undefined;
};

/** @internal */
export const UsersSetUserInfoGlobals$outboundSchema: z.ZodType<
    UsersSetUserInfoGlobals$Outbound,
    z.ZodTypeDef,
    UsersSetUserInfoGlobals
> = z.object({
    accessToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersSetUserInfoGlobals$ {
    /** @deprecated use `UsersSetUserInfoGlobals$inboundSchema` instead. */
    export const inboundSchema = UsersSetUserInfoGlobals$inboundSchema;
    /** @deprecated use `UsersSetUserInfoGlobals$outboundSchema` instead. */
    export const outboundSchema = UsersSetUserInfoGlobals$outboundSchema;
    /** @deprecated use `UsersSetUserInfoGlobals$Outbound` instead. */
    export type Outbound = UsersSetUserInfoGlobals$Outbound;
}

/** @internal */
export const UsersSetUserInfoResponse$inboundSchema: z.ZodType<
    UsersSetUserInfoResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.SuccessfulRequest$inboundSchema,
    components.BadRequestError$inboundSchema,
    components.AuthenticationFailedError$inboundSchema,
]);

/** @internal */
export type UsersSetUserInfoResponse$Outbound =
    | components.SuccessfulRequest$Outbound
    | components.BadRequestError$Outbound
    | components.AuthenticationFailedError$Outbound;

/** @internal */
export const UsersSetUserInfoResponse$outboundSchema: z.ZodType<
    UsersSetUserInfoResponse$Outbound,
    z.ZodTypeDef,
    UsersSetUserInfoResponse
> = z.union([
    components.SuccessfulRequest$outboundSchema,
    components.BadRequestError$outboundSchema,
    components.AuthenticationFailedError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersSetUserInfoResponse$ {
    /** @deprecated use `UsersSetUserInfoResponse$inboundSchema` instead. */
    export const inboundSchema = UsersSetUserInfoResponse$inboundSchema;
    /** @deprecated use `UsersSetUserInfoResponse$outboundSchema` instead. */
    export const outboundSchema = UsersSetUserInfoResponse$outboundSchema;
    /** @deprecated use `UsersSetUserInfoResponse$Outbound` instead. */
    export type Outbound = UsersSetUserInfoResponse$Outbound;
}
