/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CharacterId = {
    characterId: number;
};

/** @internal */
export namespace CharacterId$ {
    export const inboundSchema: z.ZodType<CharacterId, z.ZodTypeDef, unknown> = z.object({
        characterId: z.number().int(),
    });

    export type Outbound = {
        characterId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CharacterId> = z.object({
        characterId: z.number().int(),
    });
}
