/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const DefaultMessageQuotaExceededError = {
    YouHaveExceededYourMessageQuotaToSendMoreMessagesPleaseUpgradeYourPlanOrWaitUntilYourSubscriptionRenews:
        "You have exceeded your message quota. To send more messages, please upgrade your plan or wait until your subscription renews.",
} as const;
export type DefaultMessageQuotaExceededError = ClosedEnum<typeof DefaultMessageQuotaExceededError>;

export type DefaultMessageQuotaExceeded = {
    success?: boolean | undefined;
    error: DefaultMessageQuotaExceededError;
};

/** @internal */
export const DefaultMessageQuotaExceededError$inboundSchema: z.ZodNativeEnum<
    typeof DefaultMessageQuotaExceededError
> = z.nativeEnum(DefaultMessageQuotaExceededError);

/** @internal */
export const DefaultMessageQuotaExceededError$outboundSchema: z.ZodNativeEnum<
    typeof DefaultMessageQuotaExceededError
> = DefaultMessageQuotaExceededError$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DefaultMessageQuotaExceededError$ {
    /** @deprecated use `DefaultMessageQuotaExceededError$inboundSchema` instead. */
    export const inboundSchema = DefaultMessageQuotaExceededError$inboundSchema;
    /** @deprecated use `DefaultMessageQuotaExceededError$outboundSchema` instead. */
    export const outboundSchema = DefaultMessageQuotaExceededError$outboundSchema;
}

/** @internal */
export const DefaultMessageQuotaExceeded$inboundSchema: z.ZodType<
    DefaultMessageQuotaExceeded,
    z.ZodTypeDef,
    unknown
> = z.object({
    success: z.boolean().default(false),
    error: DefaultMessageQuotaExceededError$inboundSchema,
});

/** @internal */
export type DefaultMessageQuotaExceeded$Outbound = {
    success: boolean;
    error: string;
};

/** @internal */
export const DefaultMessageQuotaExceeded$outboundSchema: z.ZodType<
    DefaultMessageQuotaExceeded$Outbound,
    z.ZodTypeDef,
    DefaultMessageQuotaExceeded
> = z.object({
    success: z.boolean().default(false),
    error: DefaultMessageQuotaExceededError$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DefaultMessageQuotaExceeded$ {
    /** @deprecated use `DefaultMessageQuotaExceeded$inboundSchema` instead. */
    export const inboundSchema = DefaultMessageQuotaExceeded$inboundSchema;
    /** @deprecated use `DefaultMessageQuotaExceeded$outboundSchema` instead. */
    export const outboundSchema = DefaultMessageQuotaExceeded$outboundSchema;
    /** @deprecated use `DefaultMessageQuotaExceeded$Outbound` instead. */
    export type Outbound = DefaultMessageQuotaExceeded$Outbound;
}
