/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SuccessfulRequest = {
    success?: boolean | undefined;
};

/** @internal */
export namespace SuccessfulRequest$ {
    export const inboundSchema: z.ZodType<SuccessfulRequest, z.ZodTypeDef, unknown> = z.object({
        success: z.boolean().default(true),
    });

    export type Outbound = {
        success: boolean;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SuccessfulRequest> = z.object({
        success: z.boolean().default(true),
    });
}
